name = "malahayati-discord-ai"
main = "src/index.ts"
compatibility_date = "2024-02-27"
usage_model = "bundled"
account_id = "8fda878e695582341e9736656cb947ad"
env = { }

[triggers]
crons = [ ]

[ai]
binding = "AI"
